### ISSUE TITLE
 Fail at composer part of the installation of OLab4

### ISSUE THREAD

**Issue by vangelius** [olab/OLab4#3]
Needed help please!

Hi, yes, I'm giving a try to OLab4 and I'm almost there with the installation but when in /var/www/OLab4 when i try as root

php composer.phar update

Then at the end of the installation, i got some errors! it's like the repository files aren't there anymore? Could you please help me here with this part of the installation?What to do? What I'm doing wrong? etc  
Question: Do you have a link to the old Olab 3.x versions?   Greetings! from Rodrigo

Log message with the errors:
°
php composer.phar update

Token (hidden): 
Token stored successfully.                                                          
  [RuntimeException]                                                           
  Failed to execute git clone --mirror 'https://***:***@github.com/EntradaPro  
  ject/entrada-1x-api.git' '/root/.cache/composer/vcs/git-github.com-EntradaP  
  roject-entrada-1x-api.git/'                                                  
                                                                               
  remote: Repository not found.                                                
  fatal: repository 'https://***:***@github.com/EntradaProject/entrada-1x-api  
  .git/' not found                                   
°

**Comment by a-zharkov** [comment]
Hey.

> Do you have a link to the old Olab 3.x versions?

https://github.com/olab/Open-Labyrinth/releases

**Comment by vangelius** [comment]
Hi a-zharkov!  Thank you very much för the versions link!  Do you know something about the below Error Repository issue with the version OLab4?  Greetings!   Rodrigo
remote: Repository not found.
fatal: repository 'https://***:***@github.com/EntradaProject/entrada-1x-api
.git/' not found
