### ISSUE TITLE
Running process stops when it wants to install docker container!

### ISSUE THREAD

**Issue by mix49** [olab/OLab4#4]
I decided to setup my own OLab4 server on Ubuntu 18.04. After docker installation, I ran this command to install container:

$ docker-compose up -d 
The process stops without any error messages in step 12:

Step 12/48 : RUN easy_install supervisor
 ---> Running in da5efb1b5263
Searching for supervisor
Reading https://pypi.python.org/simple/supervisor/

Would you please let me know where the problem is? I increased my VM resource like HDD capacity from 60GB to 120GB and installing Python before starting docker-compose but they could not efficient.

Thanks in advance.

**Comment by RotateAt60MPH** [comment]
@mix49 I have checked in a change to the DockerFile to use 'pip' instead of 'easy_install' to install supervisord.  Please pull the latest code from the 4.0dev branch and re-try creating the container.  Ensure that you have _completely_ deleted the partial container before reattempting the container creation.

**Comment by RotateAt60MPH** [comment]
I am wondering if the problem was because the installer could not download the supervisor source tar ball.  Something to check...

**Comment by mastermagic98** [comment]
After install I can`t login Olab4.
login: demo
password: oldemo
It is wrong

**Comment by FatemeBordbar** [comment]
> After install I can`t login Olab4. login: demo password: oldemo It is wrong

hi ,
My problem is the same
Of course, it does not give token because the file is not available
Were you able to go to the next stage?

**Comment by mastermagic98** [comment]
> >  Were you able to go to the next stage?

No. Unfortunately

**Comment by RotateAt60MPH** [comment]
Closed as this issue applies to to a now unsupported version of OLab.
