### ISSUE TITLE
Installation - Entrada repo is missing!

### ISSUE THREAD

**Issue by nor4a** [olab/OLab4#5]
[RuntimeException]
  Failed to execute git clone --mirror 'https://***:***@github.com/EntradaProject/entrada-1x-api.git' '/root/.composer/cache/vcs/git-github.com-EntradaProject-entrada-1x-api.git/'
Cloning into bare repository '/root/.composer/cache/vcs/git-github.com-EntradaProject-entrada-1x-api.git'...
  remote: Repository not found.
fatal: repository 'https://***:***@github.com/EntradaProject/entrada-1x-api.git/' not found

**Comment by RotateAt60MPH** [comment]
This dependency was addressed in the latest refactoring.   I'll be merging to master and making the fix available within the next month as it's lumped in with a biggest repo reorganization
